name: Dialyzer

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["22.2", "23.0"]
        elixir: [1.10.3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: MIX_ENV=ci mix deps.get
      - run: MIX_ENV=ci mix deps.compile
      - run: MIX_ENV=ci mix quality.ci
