name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 26.0
              elixir: 1.15.7-otp-26
          - pair:
              otp: 25.2
              elixir: 1.14.5-otp-25
          - pair:
              otp: 24.2
              elixir: 1.12.3-otp-24
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          epmd -daemon
          mix deps.get
          mix deps.compile
      - name: Run tests
        run: |
          mix test
